name: aidventure
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip
  - python=3.9.7
  - pytorch
  - torchvision
  - torchaudio
  - websockets=12.0
  - transformers=4.44
  - sentencepiece
  - accelerate
  - protobuf
  - pytorch-cuda