name: aidventure
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip
  - python=3.9.7
  - pytorch=1.12
  - websockets=10.0
  - transformers=4.21
  - sentencepiece
  - accelerate=0.12.0