name: aidventure
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip
  - python=3.9.7
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - websockets=10.4
  - transformers=4.27
  - sentencepiece
  - accelerate