name: aidventure
channels:
  - conda-forge
  - pytorch
dependencies:
  - pip
  - python=3.9.7
  - pytorch
  - websockets=10.4
  - transformers=4.27
  - sentencepiece
  - accelerate
  - torchvision
  - torchaudio
  - cpuonly
